# Field instance.
field.field_settings.textfield_attr:
  type: mapping
  label: Textfield with attributes field settings
  mapping:
    attr0_values:
      type: sequence
      sequence:
        type: label
    attr1_values:
      type: sequence
      sequence:
        type: label
    attr0_name:
      type: string
    attr1_name:
      type: string
field.field_settings.textarea_attr:
  type: mapping
  label: Textarea with attributes field settings
  mapping:
    attr0_values:
      type: sequence
      sequence:
        type: label
    attr1_values:
      type: sequence
      sequence:
        type: label
    attr0_name:
      type: string
    attr1_name:
      type: string

# Default value.
field.value.textfield_attr:
  type: mapping
  label: Default value
  mapping:
    attr0:
      type: string
      label: Attribute One
    attr1:
      type: string
      label: Attribute Two
    value:
      type: string
      label: Value
field.value.textarea_attr:
  type: mapping
  label: Default value
  mapping:
    attr0:
      type: string
      label: Attribute One
    attr1:
      type: string
      label: Attribute Two
    value:
      type: text
      label: Value
    format:
      type: string
      label: Format

# Field formatter.
field.formatter.settings.attr_default:
  type: mapping
  label: Attr default formatter settings
  mapping:
    override_label:
      type: boolean


# Default value.
field.value.related_item:
  type: mapping
  label: Default value
  mapping:
    identifier:
      type: string
      label: Identifier
    identifier_type:
      type: string
      label: Identifier Type
    number:
      type: string
      label: Number
    title:
      type: string
      label: Title
